apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: diabetic-api-sm
  namespace: monitoring          # where kube-prometheus-stack is installed
  labels:
    release: monitoring-stack    # MUST match your Prometheus Helm release name
spec:
  selector:
    matchLabels:
      app: diabetic-api          # MUST match labels on the *Service*
  namespaceSelector:
    matchNames:
      - default                  # diabetic-api runs in default namespace
  endpoints:
    - port: http                 # MUST match the port *name* on the Service
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
