name: 04 - Jenkins EC2 - Fetch Admin Password

on:
  workflow_dispatch:
    inputs:
      public_dns:
        description: "EC2 public DNS"
        required: true

jobs:
  password:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/jenkins-ec2-key
          chmod 600 ~/.ssh/jenkins-ec2-key
          printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" >> ~/.ssh/config

      - name: Fetch Jenkins initial admin password
        run: |
          PUBLIC_DNS="${{ inputs.public_dns }}"

          for i in {1..20}; do
            if ssh -i ~/.ssh/jenkins-ec2-key ec2-user@"${PUBLIC_DNS}" "sudo test -f /var/lib/jenkins/secrets/initialAdminPassword"; then
              ssh -i ~/.ssh/jenkins-ec2-key ec2-user@"${PUBLIC_DNS}" \
                "sudo cat /var/lib/jenkins/secrets/initialAdminPassword"
              exit 0
            fi
            sleep 30
          done

          ssh -i ~/.ssh/jenkins-ec2-key ec2-user@"${PUBLIC_DNS}" \
            "sudo systemctl status jenkins --no-pager || true"
          ssh -i ~/.ssh/jenkins-ec2-key ec2-user@"${PUBLIC_DNS}" \
            "sudo journalctl -u jenkins --no-pager | tail -n 80 || true"
          exit 1
